apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  annotations:
  name: icp4adeploy
  namespace: cp4ba
spec:
  bai_configuration:
    business_performance_center:
      all_users_access: true
    image_credentials:
      registry: cp.icr.io/cp/cp4a
  resource_registry_configuration:
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 22.0.2
  ecm_configuration:
    cmis:
      arch:
        amd64: 3 - Most preferred
      auto_scaling:
        enabled: false
        max_replicas: 3
        min_replicas: 2
        target_cpu_utilization_percentage: 80
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cmis
        tag: 22.0.2
      logging_enabled: false
      monitor_enabled: false
      replica_count: 2
      resources:
        limits:
          cpu: 1
          memory: 1536Mi
        requests:
          cpu: 500m
          memory: 256Mi
    cpe:
      arch:
        amd64: 3 - Most preferred
      auto_scaling:
        enabled: false
        max_replicas: 3
        min_replicas: 2
        target_cpu_utilization_percentage: 80
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cpe
        tag: 22.0.2
      logging_enabled: false
      monitor_enabled: false
      replica_count: 2
      resources:
        limits:
          cpu: 1
          memory: 4096Mi
        requests:
          cpu: 500m
          memory: 2500Mi
  no_log: false
  olm_ibm_license: true
  bastudio_configuration:
    images:
      bastudio:
        repository: cp.icr.io/cp/cp4a/bas/bastudio
        tag: 22.0.2
    jms_server:
      image:
        repository: cp.icr.io/cp/cp4a/bas/jms
        tag: 22.0.2
    playback_server:
      images:
        db_job:
          repository: cp.icr.io/cp/cp4a/bas/solution-server-helmjob-db
          tag: 22.0.2
        solution_server:
          repository: cp.icr.io/cp/cp4a/bas/solution-server
          tag: 22.0.2
  workflow_authoring_configuration:
    bas_auto_import_job:
      repository: cp.icr.io/cp/cp4a/baw/toolkit-installer
      tag: 22.0.2
    case:
      init_job_image:
        repository: cp.icr.io/cp/cp4a/baw/workflow-server-case-initialization
        tag: 22.0.2
    content_integration:
      init_job_image:
        repository: cp.icr.io/cp/cp4a/baw/iaws-ps-content-integration
        tag: 22.0.2
    ibm_workplace_job:
      repository: cp.icr.io/cp/cp4a/baw/iaws-ibm-workplace
      tag: 22.0.2
    image:
      repository: cp.icr.io/cp/cp4a/bas/workflow-authoring
      tag: 22.0.2
    jms:
      image:
        repository: cp.icr.io/cp/cp4a/baw/jms
        tag: 22.0.2
    pfs_bpd_database_init_job:
      repository: cp.icr.io/cp/cp4a/baw/pfs-bpd-database-init-prod
      tag: 22.0.2
    upgrade_job:
      repository: cp.icr.io/cp/cp4a/baw/workflow-server-dbhandling
      tag: 22.0.2
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator
      tag: 22.0.2
  debug: false
  pfs_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/baw/pfs-prod
      tag: 22.0.2
  baml_configuration:
    intelligent_task_prioritization:
      image:
        repository: cp.icr.io/cp/cp4a/baw/bui-task-prioritization
        tag: 22.0.2
    workforce_insights:
      image:
        repository: cp.icr.io/cp/cp4a/baw/workforce-insights
        tag: 22.0.2
  ibm_license: accept
  appVersion: 22.0.2
  shared_configuration:
    sc_cpe_limited_storage: false
    sc_deployment_type: Starter
    sc_optional_components: 'bai,baml,baw_authoring,case,content_integration,pfs,workstreams'
    no_log: false
    image_pull_secrets:
      - admin.registrykey
    trusted_certificate_list: []
    sc_deployment_patterns: workflow-workstreams
    sc_deployment_baw_license: non-production
    storage_configuration:
      sc_block_storage_classname: ocs-storagecluster-ceph-rbd
      sc_dynamic_storage_classname: ocs-storagecluster-cephfs
      sc_fast_file_storage_classname: ocs-storagecluster-cephfs
      sc_medium_file_storage_classname: ocs-storagecluster-cephfs
      sc_slow_file_storage_classname: ocs-storagecluster-cephfs
    debug: false
    root_ca_secret: '{{ meta.name }}-root-ca'
    sc_content_initialization: true
    sc_deployment_license: non-production
    images:
      dbcompatibility_init_container:
        repository: cp.icr.io/cp/cp4a/aae/dba-dbcompatibility-initcontainer
        tag: 22.0.2
      keytool_init_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-initcontainer
        tag: 22.0.2
      keytool_job_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-jobcontainer
        tag: 22.0.2
      openldap:
        repository: cp.icr.io/cp/cp4a/demo/openldap
        tag: 1.5.0.2
      umsregistration_initjob:
        repository: cp.icr.io/cp/cp4a/aae/dba-umsregistration-initjob
        tag: 22.0.2
    sc_ingress_enable: false
    sc_image_repository: cp.icr.io
    sc_deployment_platform: OCP
    sc_deployment_fncm_license: non-production